#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# PartMgr GUI
#
# Copyright 2014 Michael Buesch <m@bues.ch>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

import sys
if sys.version_info.major < 3:
	raise Exception("partmgr needs Python 3.x")

from partmgr.gui.mainwindow import *


def main(argv):
	app = QApplication(argv)
	mainwnd = PartMgrMainWindow()
	if len(argv) == 2:
		if not mainwnd.loadDatabaseFile(argv[1]):
			return 1
	mainwnd.show()
	return app.exec()

if __name__ == "__main__":
	sys.exit(main(sys.argv))
